import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service – TaxSort",
  description: "TaxSort terms of service. Read the terms and conditions for using the TaxSort mobile app and website.",
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main>
        <section style={{ background: "#e8f0e5" }} className="py-16 px-4">
          <div className="max-w-3xl mx-auto text-center">
            <h1 className="text-4xl font-bold text-gray-900 mb-2">Terms of Service</h1>
            <p className="text-gray-500 text-sm">Last updated: May 23, 2026</p>
          </div>
        </section>

        <section className="py-16 px-4">
          <div className="max-w-3xl mx-auto">
            <div className="space-y-10 text-gray-700 leading-relaxed">

              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-3">1. Acceptance of Terms</h2>
                <p className="text-sm">By downloading, installing, or using TaxSort (&ldquo;the App&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, do not use the App. These terms apply to all users of TaxSort, including the mobile app (iOS and Android) and the website at taxsort.app.</p>
              </div>

              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-3">2. Description of Service</h2>
                <p className="text-sm">TaxSort is a mobile application that helps freelancers, self-employed individuals, and gig workers track business expenses, scan receipts, log mileage, and generate tax reports. TaxSort is a record-keeping and organizational tool — it does not provide tax advice, legal advice, or accounting services. Always consult a qualified tax professional before filing your taxes.</p>
              </div>

              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-3">3. Accounts and Registration</h2>
                <ul className="list-disc pl-5 space-y-2 text-sm">
                  <li>You must create an account to use TaxSort. You are responsible for maintaining the confidentiality of your login credentials.</li>
                  <li>You must provide accurate and complete information when creating your account.</li>
                  <li>You are responsible for all activity that occurs under your account.</li>
                  <li>You must be at least 18 years old to use TaxSort.</li>
                </ul>
              </div>

              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-3">4. Subscriptions and Billing</h2>
                <ul className="list-disc pl-5 space-y-2 text-sm">
                  <li>TaxSort offers a free plan and a Pro plan billed annually at $44.99 USD/year.</li>
                  <li>Subscriptions are processed through Apple App Store or Google Play and are subject to their respective terms.</li>
                  <li>Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current billing period.</li>
                  <li>You can manage and cancel your subscription in your App Store or Google Play account settings.</li>
                  <li>We do not offer refunds except where required by applicable law or app store policies.</li>
                </ul>
              </div>

              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-3">5. Acceptable Use</h2>
                <p className="text-sm mb-3">You agree not to:</p>
                <ul className="list-disc pl-5 space-y-1 text-sm">
                  <li>Use TaxSort for any unlawful purpose or in violation of any applicable laws</li>
                  <li>Attempt to reverse engineer, decompile, or disassemble the App</li>
                  <li>Upload false, misleading, or fraudulent financial data</li>
                  <li>Attempt to gain unauthorized access to other users&apos; accounts or our systems</li>
                  <li>Use the App to facilitate tax evasion or fraud</li>
                </ul>
              </div>

              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-3">6. Disclaimer of Tax and Financial Advice</h2>
                <p className="text-sm">TaxSort is a record-keeping tool only. The information, reports, and categorizations generated by TaxSort do not constitute tax advice, financial advice, or legal advice. Tax laws change frequently and vary by jurisdiction. TaxSort makes no representations or warranties regarding the accuracy, completeness, or suitability of any information for your specific tax situation. You are solely responsible for the accuracy of your tax filings. Always consult a qualified tax professional or accountant.</p>
              </div>

              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-3">7. Intellectual Property</h2>
                <p className="text-sm">TaxSort and all related content, features, and functionality are owned by Elitech Pro Services Inc. and are protected by copyright, trademark, and other intellectual property laws. You may not copy, modify, distribute, or create derivative works without our express written permission.</p>
              </div>

              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-3">8. Limitation of Liability</h2>
                <p className="text-sm">To the maximum extent permitted by law, TaxSort and Elitech Pro Services Inc. shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of data, revenue, or profits, arising from your use of the App. Our total liability to you for any claims arising from these terms or your use of TaxSort shall not exceed the amount you paid for the App in the 12 months preceding the claim.</p>
              </div>

              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-3">9. Termination</h2>
                <p className="text-sm">We reserve the right to suspend or terminate your account at any time if you violate these terms. You may delete your account at any time by contacting us at support@taxsort.app. Upon termination, your right to use the App ceases immediately.</p>
              </div>

              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-3">10. Changes to These Terms</h2>
                <p className="text-sm">We may update these terms from time to time. We will notify you of significant changes via email or in-app notification. Continued use of TaxSort after changes are posted constitutes your acceptance of the revised terms.</p>
              </div>

              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-3">11. Governing Law</h2>
                <p className="text-sm">These terms are governed by the laws of the Province of Ontario, Canada, without regard to conflict of law principles. Any disputes shall be resolved in the courts of Ontario, Canada.</p>
              </div>

              <div>
                <h2 className="text-xl font-bold text-gray-900 mb-3">12. Contact Us</h2>
                <p className="text-sm">Questions about these terms? Contact us at{" "}
                  <a href="mailto:support@taxsort.app" className="underline" style={{ color: "#2a7a3b" }}>
                    support@taxsort.app
                  </a>
                </p>
              </div>

              <p className="text-xs text-gray-400 pt-4 border-t border-gray-100">© 2026 Elitech Pro Services Inc. All rights reserved.</p>

            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
